CREATE TABLE productos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(100) NOT NULL,
    precio NUMBER(10,2) NOT NULL,
    stock NUMBER NOT NULL,
    CONSTRAINT pk_productos PRIMARY KEY (id)
);

INSERT INTO productos (nombre, precio, stock)
VALUES ('Laptop Lenovo', 2500000, 10);

INSERT INTO productos (nombre, precio, stock)
VALUES ('Mouse Logitech', 85000, 25);

INSERT INTO productos (nombre, precio, stock)
VALUES ('Teclado Mecánico', 180000, 15);

INSERT INTO productos (nombre, precio, stock)
VALUES ('Monitor Samsung', 950000, 8);

INSERT INTO productos (nombre, precio, stock)
VALUES ('Audífonos Sony', 320000, 12);

COMMIT;

SELECT * FROM productos ORDER BY id;